apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jokes-ts.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jokes-ts.labels" . | nindent 4 }}
data:
  DB_TYPE: {{ .Values.env.db.type | quote }}
  DB_USERNAME: {{ .Values.env.db.username | quote }}
  DB_DATABASE: {{ .Values.env.db.database | quote }}
  DB_PORT: {{ .Values.env.db.port }}
