apiVersion: v2
name: jokes-ts
description: Jokes Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1
dependencies:
  - name: postgresql
    version: 12.7.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
